// Generated by https://quicktype.io

export interface RespuestaReportes {
    ok:              boolean;
    pagina:          number;
    ReportesTotales: Reporte[];
}

export interface Reporte {
    _id?:         string;
    nombre?:      string;
    abonado?:     number;
    email?:       string;
    tlfContacto?: number;
    falla?:       string;
    tipoFalla?:   string;
    usuario?:     Usuario;
    created?:     string;
    
}

export interface Usuario {
    _id?:    string;
    nombre?: string;
    email?:  string;
    password?: string;
}
