// Generated by https://quicktype.io

export interface RespuestaReports {
    ok:              boolean;
    pagina:          number;
    ReportesTotales: Reports[];
}

export interface Reports {
    _id?:         string;
    nombre?:      string;
    abonado?:     number;
    email?:       string;
    tlfContacto?: number;
    falla?:       string;
    tipoFalla?:   string;
    usuario?:     Usuario;
    created?:     string;
   
}

export interface Usuario {
    _id?:    string;
    nombre?: string;
    email?:  string;
   
}
